type User @table {
  username: String!
  createdAt: Timestamp!
  email: String
  profilePictureUrl: String
  bio: String
}

type Trip @table {
  name: String!
  startDate: Date!
  endDate: Date!
  isPublic: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  user: User!
}

type Location @table {
  name: String!
  orderInTrip: Int!
  description: String
  arrivalDate: Date
  departureDate: Date
  notes: String
  trip: Trip!
}

type Photo @table {
  imageUrl: String!
  createdAt: Timestamp!
  caption: String
  trip: Trip!
  location: Location
}

type Comment @table {
  content: String!
  createdAt: Timestamp!
  user: User!
  trip: Trip!
}